[package]
name = "asciinet"
version = "0.1.0"
authors = ["Fernando Fernandez Mancera <ffmancera@riseup.net>"]
edition = "2018"

[[bin]]
name = "asciinet"
path = "src/asciinet.rs"

[dependencies]
nispor = "1.0.1"
